<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r) 
on 2013-04-26 23:36:17 and allows to alter the behaviour of 'PluginResult' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\User;

/**
 * A PluginResult reflects a state resulting from executing a workflow plugin.
 */
class PluginResultDocument extends \Honeybee\Domain\User\Base\PluginResultDocument
{
    
}
