<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-07-30 00:04:12 and allows to alter the behaviour of the 'User' module.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\User;

use Honeybee\Domain\User\Base;

/**
 * The UserModule class reflects the declared structure of the 'User' entity.
 * It holds the meta data necessary to manage/initiate 'UserDocument' lifecycles.
 */
class UserModule extends Base\UserModule
{

}
