<?php
/*                  AUTOGENERATED SKELETON CLASS
This skeleton class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-07-30 00:04:13 and allows to alter the behaviour of 'User' documents.
This file is only generated if doesn't exist so eventual modifications are safe. */

namespace Honeybee\Domain\User;

use Honeybee\Domain\User\Base;

/**
 * Holds the structure definition for User documents.
 */
class UserDocument extends Base\UserDocument
{

}
