<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r) 
on 2013-04-28 00:55:58 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of 'User' documents,
then the 'UserDocument' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\User\Base;

/**
 * Serves as the base class to the 'User' document skeleton.
 */
abstract class UserDocument extends \Honeybee\Core\Dat0r\Document
{ 
    /**
     * Returns an 'User' document's username.
     *
     * @return string
     */
    public function getUsername()
    {
        return $this->getValue('username');
    }

    /**
     * Sets an 'User' document's username.
     *
     * @param string $username
     */
    public function setUsername($username)
    {
        $this->setValue('username', $username);
    }

    /**
     * Returns an 'User' document's firstname.
     *
     * @return string
     */
    public function getFirstname()
    {
        return $this->getValue('firstname');
    }

    /**
     * Sets an 'User' document's firstname.
     *
     * @param string $firstname
     */
    public function setFirstname($firstname)
    {
        $this->setValue('firstname', $firstname);
    }

    /**
     * Returns an 'User' document's lastname.
     *
     * @return string
     */
    public function getLastname()
    {
        return $this->getValue('lastname');
    }

    /**
     * Sets an 'User' document's lastname.
     *
     * @param string $lastname
     */
    public function setLastname($lastname)
    {
        $this->setValue('lastname', $lastname);
    }

    /**
     * Returns an 'User' document's email.
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->getValue('email');
    }

    /**
     * Sets an 'User' document's email.
     *
     * @param string $email
     */
    public function setEmail($email)
    {
        $this->setValue('email', $email);
    }

    /**
     * Returns an 'User' document's role.
     *
     * @return string
     */
    public function getRole()
    {
        return $this->getValue('role');
    }

    /**
     * Sets an 'User' document's role.
     *
     * @param string $role
     */
    public function setRole($role)
    {
        $this->setValue('role', $role);
    }

    /**
     * Returns an 'User' document's passwordHash.
     *
     * @return string
     */
    public function getPasswordhash()
    {
        return $this->getValue('passwordHash');
    }

    /**
     * Sets an 'User' document's passwordHash.
     *
     * @param string $passwordHash
     */
    public function setPasswordhash($passwordHash)
    {
        $this->setValue('passwordHash', $passwordHash);
    }

    /**
     * Returns an 'User' document's authToken.
     *
     * @return string
     */
    public function getAuthtoken()
    {
        return $this->getValue('authToken');
    }

    /**
     * Sets an 'User' document's authToken.
     *
     * @param string $authToken
     */
    public function setAuthtoken($authToken)
    {
        $this->setValue('authToken', $authToken);
    }

    /**
     * Returns an 'User' document's tokenExpireDate.
     *
     * @return string
     */
    public function getTokenexpiredate()
    {
        return $this->getValue('tokenExpireDate');
    }

    /**
     * Sets an 'User' document's tokenExpireDate.
     *
     * @param string $tokenExpireDate
     */
    public function setTokenexpiredate($tokenExpireDate)
    {
        $this->setValue('tokenExpireDate', $tokenExpireDate);
    }

    /**
     * Returns an 'User' document's meta.
     *
     * @return array
     */
    public function getMeta()
    {
        return $this->getValue('meta');
    }

    /**
     * Sets an 'User' document's meta.
     *
     * @param array $meta
     */
    public function setMeta($meta)
    {
        $this->setValue('meta', $meta);
    }

    /**
     * Returns an 'User' document's workflowTicket.
     *
     * @return WorkflowTicketModule
     */
    public function getWorkflowticket()
    {
        return $this->getValue('workflowTicket');
    }

    /**
     * Sets an 'User' document's workflowTicket.
     *
     * @param WorkflowTicketModule $workflowTicket
     */
    public function setWorkflowticket($workflowTicket)
    {
        $this->setValue('workflowTicket', $workflowTicket);
    }
}
