<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-07-30 00:04:13 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of 'User' documents,
then the 'UserDocument' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\User\Base;

use Honeybee\Core\Dat0r;

/**
 * Serves as the base class to the 'User' document skeleton.
 */
abstract class UserDocument extends Dat0r\Document
{
    /**
     * Returns an 'User' document's username.
     *
     * @return 
     */
    public function getUsername()
    {
        return $this->getValue('username');
    }

    /**
     * Sets an 'User' document's username.
     *
     * @param  $username
     */
    public function setUsername($username)
    {
        $this->setValue('username', $username);
    }

    /**
     * Returns an 'User' document's email.
     *
     * @return 
     */
    public function getEmail()
    {
        return $this->getValue('email');
    }

    /**
     * Sets an 'User' document's email.
     *
     * @param  $email
     */
    public function setEmail($email)
    {
        $this->setValue('email', $email);
    }

    /**
     * Returns an 'User' document's role.
     *
     * @return 
     */
    public function getRole()
    {
        return $this->getValue('role');
    }

    /**
     * Sets an 'User' document's role.
     *
     * @param  $role
     */
    public function setRole($role)
    {
        $this->setValue('role', $role);
    }

    /**
     * Returns an 'User' document's firstname.
     *
     * @return 
     */
    public function getFirstname()
    {
        return $this->getValue('firstname');
    }

    /**
     * Sets an 'User' document's firstname.
     *
     * @param  $firstname
     */
    public function setFirstname($firstname)
    {
        $this->setValue('firstname', $firstname);
    }

    /**
     * Returns an 'User' document's lastname.
     *
     * @return 
     */
    public function getLastname()
    {
        return $this->getValue('lastname');
    }

    /**
     * Sets an 'User' document's lastname.
     *
     * @param  $lastname
     */
    public function setLastname($lastname)
    {
        $this->setValue('lastname', $lastname);
    }

    /**
     * Returns an 'User' document's passwordHash.
     *
     * @return 
     */
    public function getPasswordHash()
    {
        return $this->getValue('passwordHash');
    }

    /**
     * Sets an 'User' document's passwordHash.
     *
     * @param  $passwordHash
     */
    public function setPasswordHash($passwordHash)
    {
        $this->setValue('passwordHash', $passwordHash);
    }

    /**
     * Returns an 'User' document's authToken.
     *
     * @return 
     */
    public function getAuthToken()
    {
        return $this->getValue('authToken');
    }

    /**
     * Sets an 'User' document's authToken.
     *
     * @param  $authToken
     */
    public function setAuthToken($authToken)
    {
        $this->setValue('authToken', $authToken);
    }

    /**
     * Returns an 'User' document's tokenExpireDate.
     *
     * @return 
     */
    public function getTokenExpireDate()
    {
        return $this->getValue('tokenExpireDate');
    }

    /**
     * Sets an 'User' document's tokenExpireDate.
     *
     * @param  $tokenExpireDate
     */
    public function setTokenExpireDate($tokenExpireDate)
    {
        $this->setValue('tokenExpireDate', $tokenExpireDate);
    }

    /**
     * Returns an 'User' document's meta.
     *
     * @return 
     */
    public function getMeta()
    {
        return $this->getValue('meta');
    }

    /**
     * Sets an 'User' document's meta.
     *
     * @param  $meta
     */
    public function setMeta($meta)
    {
        $this->setValue('meta', $meta);
    }

    /**
     * Returns an 'User' document's workflowTicket.
     *
     * @return 
     */
    public function getWorkflowTicket()
    {
        return $this->getValue('workflowTicket');
    }

    /**
     * Sets an 'User' document's workflowTicket.
     *
     * @param  $workflowTicket
     */
    public function setWorkflowTicket($workflowTicket)
    {
        $this->setValue('workflowTicket', $workflowTicket);
    }
}
