<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r)
on 2013-08-05 22:31:14 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'User' module,
then the 'UserModule' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\User\Base;

use Dat0r\Core\Field\AggregateField;
use Dat0r\Core\Field\KeyValueField;
use Dat0r\Core\Field\TextField;
use Honeybee\Core\Dat0r;

/**
 * Serves as the base class to the 'User'' module skeleton.
 */
abstract class UserModule extends Dat0r\Module
{
    /**
     * Creates a new UserModule instance.
     */
    protected function __construct()
    {
        parent::__construct(
            'User',
            array(
                TextField::create(
                    'username',
                    array(
                        'mandatory' => true,
                    )
                ),
                TextField::create(
                    'email',
                    array(
                        'mandatory' => true,
                    )
                ),
                TextField::create(
                    'role',
                    array(
                        'mandatory' => true,
                    )
                ),
                TextField::create(
                    'firstname',
                    array()
                ),
                TextField::create(
                    'lastname',
                    array()
                ),
                TextField::create(
                    'passwordHash',
                    array()
                ),
                TextField::create(
                    'authToken',
                    array()
                ),
                TextField::create(
                    'tokenExpireDate',
                    array()
                ),
                KeyValueField::create(
                    'meta',
                    array(
                        'constraints' => array(
                            'value_type' => 'dynamic',
                        ),
                    )
                ),
                AggregateField::create(
                    'workflowTicket',
                    array(
                        'modules' => array(
                            '\\Honeybee\\Domain\\User\\WorkflowTicketModule',
                        ),
                    )
                ),
            ),
            array(
                'prefix' => 'user',
                'identifier_field' => 'identifier',
                'slugPattern' => '{username}-{shortId}',
            )
        );
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return '\\Honeybee\\Domain\\User\\UserDocument';
    }
}
