<?php
/*              AUTOGENERATED CODE - DO NOT EDIT !
This base class was generated by the Dat0r library (https://github.com/berlinonline/Dat0r) 
on 2013-04-28 00:55:58 and is closed to modifications by any meaning.
If you are looking for a place to alter the behaviour of the 'User' module,
then the 'UserModule' (skeleton) class probally might be a good place to look. */

namespace Honeybee\Domain\User\Base;

/**
 * Serves as the base class to the 'User'' module skeleton.
 */
abstract class UserModule extends \Honeybee\Core\Dat0r\Module
{
    /**
     * Creates a new UserModule instance.
     */
    protected function __construct()
    {
        parent::__construct('User', array( 
            \Dat0r\Core\Runtime\Field\TextField::create('username'), 
            \Dat0r\Core\Runtime\Field\TextField::create('firstname'), 
            \Dat0r\Core\Runtime\Field\TextField::create('lastname'), 
            \Dat0r\Core\Runtime\Field\TextField::create('email'), 
            \Dat0r\Core\Runtime\Field\TextField::create('role'), 
            \Dat0r\Core\Runtime\Field\TextField::create('passwordHash'), 
            \Dat0r\Core\Runtime\Field\TextField::create('authToken'), 
            \Dat0r\Core\Runtime\Field\TextField::create('tokenExpireDate'), 
            \Dat0r\Core\Runtime\Field\KeyValueField::create('meta', array(                  
                'constraints' => array('value_type' => 'dynamic',),  
            )), 
            \Dat0r\Core\Runtime\Field\AggregateField::create('workflowTicket', array(                  
                'aggregate_module' => 'Honeybee\\Domain\\User\\WorkflowTicketModule',  
            )), 
        ), array(             
            'prefix' => 'user',               
            'identifier_field' => 'identifier',               
            'baseModule' => '\\Honeybee\\Core\\Dat0r\\Module',               
            'baseDocument' => '\\Honeybee\\Core\\Dat0r\\Document',   
        ));
    }

    /**
     * Returns the IDocument implementor to use when creating new documents.
     *
     * @return string Fully qualified name of an IDocument implementation.
     */
    protected function getDocumentImplementor()
    {
        return 'Honeybee\Domain\User\UserDocument';
    }
}
